/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

static ast_node * clone_ast_node(const ast_node * node)
{
	if (!node) {
		return nullptr;
	}

	auto * copied = new ast_node(node->node_type, node->type, node->line_no);
	copied->integer_val = node->integer_val;
	copied->float_val = node->float_val;
	copied->name = node->name;
	copied->needScope = node->needScope;

	for (auto child: node->sons) {
		copied->insert_son_node(clone_ast_node(child));
	}

	return copied;
}

static ast_node * make_for_missing_marker()
{
	return ast_node::New(ast_operator_type::AST_OP_MAX);
}

static ast_node * make_inc_dec_expr(ast_node * lval, bool isInc, bool isPostfix)
{
	if (!lval) {
		return nullptr;
	}

	ast_node * rhsLVal = clone_ast_node(lval);
	digit_int_attr oneAttr{1, (uint32_t) lval->line_no};
	ast_node * oneNode = ast_node::New(oneAttr);
	auto op = isInc ? ast_operator_type::AST_OP_ADD : ast_operator_type::AST_OP_SUB;
	ast_node * calcNode = ast_node::New(op, rhsLVal, oneNode);
	ast_node * assignNode = ast_node::New(ast_operator_type::AST_OP_ASSIGN, lval, calcNode);

	if (!isPostfix) {
		return assignNode;
	}

	// 后缀表达式返回“旧值”：
	// x++ => (x = x + 1) - 1
	// x-- => (x = x - 1) + 1
	auto restoreOp = isInc ? ast_operator_type::AST_OP_SUB : ast_operator_type::AST_OP_ADD;
	return ast_node::New(restoreOp, assignNode, ast_node::New(oneAttr));
}

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);

// 指向创建的抽象语法树
static ast_node * ast_root;

// 向外部提供的接口函数，用于返回抽象语法树的根节点
ast_node * get_ast_root()
{
	return ast_root;
}


#line 148 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_INT = 5,                      /* T_INT  */
  YYSYMBOL_T_VOID = 6,                     /* T_VOID  */
  YYSYMBOL_T_RETURN = 7,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 8,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 9,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 10,                   /* T_WHILE  */
  YYSYMBOL_T_FOR = 11,                     /* T_FOR  */
  YYSYMBOL_T_BREAK = 12,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 13,                /* T_CONTINUE  */
  YYSYMBOL_T_CONST = 14,                   /* T_CONST  */
  YYSYMBOL_T_STATIC = 15,                  /* T_STATIC  */
  YYSYMBOL_T_SEMICOLON = 16,               /* T_SEMICOLON  */
  YYSYMBOL_T_L_PAREN = 17,                 /* T_L_PAREN  */
  YYSYMBOL_T_R_PAREN = 18,                 /* T_R_PAREN  */
  YYSYMBOL_T_L_BRACE = 19,                 /* T_L_BRACE  */
  YYSYMBOL_T_R_BRACE = 20,                 /* T_R_BRACE  */
  YYSYMBOL_T_L_BRACKET = 21,               /* T_L_BRACKET  */
  YYSYMBOL_T_R_BRACKET = 22,               /* T_R_BRACKET  */
  YYSYMBOL_T_COMMA = 23,                   /* T_COMMA  */
  YYSYMBOL_T_ASSIGN = 24,                  /* T_ASSIGN  */
  YYSYMBOL_T_SUB = 25,                     /* T_SUB  */
  YYSYMBOL_T_ADD = 26,                     /* T_ADD  */
  YYSYMBOL_T_MUL = 27,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 28,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 29,                     /* T_MOD  */
  YYSYMBOL_T_EQ = 30,                      /* T_EQ  */
  YYSYMBOL_T_NE = 31,                      /* T_NE  */
  YYSYMBOL_T_LT = 32,                      /* T_LT  */
  YYSYMBOL_T_LE = 33,                      /* T_LE  */
  YYSYMBOL_T_GT = 34,                      /* T_GT  */
  YYSYMBOL_T_GE = 35,                      /* T_GE  */
  YYSYMBOL_T_AND = 36,                     /* T_AND  */
  YYSYMBOL_T_OR = 37,                      /* T_OR  */
  YYSYMBOL_T_NOT = 38,                     /* T_NOT  */
  YYSYMBOL_T_INC = 39,                     /* T_INC  */
  YYSYMBOL_T_DEC = 40,                     /* T_DEC  */
  YYSYMBOL_LOWER_THAN_ELSE = 41,           /* LOWER_THAN_ELSE  */
  YYSYMBOL_YYACCEPT = 42,                  /* $accept  */
  YYSYMBOL_CompileUnit = 43,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 44,                   /* FuncDef  */
  YYSYMBOL_FuncFParams = 45,               /* FuncFParams  */
  YYSYMBOL_FuncFParam = 46,                /* FuncFParam  */
  YYSYMBOL_FuncArrayDimsOpt = 47,          /* FuncArrayDimsOpt  */
  YYSYMBOL_FuncArrayDims = 48,             /* FuncArrayDims  */
  YYSYMBOL_Block = 49,                     /* Block  */
  YYSYMBOL_BlockItemList = 50,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 51,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 52,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 53,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 54,                    /* VarDef  */
  YYSYMBOL_VarArrayDims = 55,              /* VarArrayDims  */
  YYSYMBOL_BasicType = 56,                 /* BasicType  */
  YYSYMBOL_Statement = 57,                 /* Statement  */
  YYSYMBOL_Expr = 58,                      /* Expr  */
  YYSYMBOL_LOrExp = 59,                    /* LOrExp  */
  YYSYMBOL_LAndExp = 60,                   /* LAndExp  */
  YYSYMBOL_EqExp = 61,                     /* EqExp  */
  YYSYMBOL_RelExp = 62,                    /* RelExp  */
  YYSYMBOL_AddExp = 63,                    /* AddExp  */
  YYSYMBOL_AddOp = 64,                     /* AddOp  */
  YYSYMBOL_MulExp = 65,                    /* MulExp  */
  YYSYMBOL_MulOp = 66,                     /* MulOp  */
  YYSYMBOL_UnaryExp = 67,                  /* UnaryExp  */
  YYSYMBOL_ForInitOpt = 68,                /* ForInitOpt  */
  YYSYMBOL_ForInit = 69,                   /* ForInit  */
  YYSYMBOL_ForCondOpt = 70,                /* ForCondOpt  */
  YYSYMBOL_ForStepOpt = 71,                /* ForStepOpt  */
  YYSYMBOL_ForExpr = 72,                   /* ForExpr  */
  YYSYMBOL_PrimaryExp = 73,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 74,             /* RealParamList  */
  YYSYMBOL_LVal = 75,                      /* LVal  */
  YYSYMBOL_ArraySubscripts = 76            /* ArraySubscripts  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  13
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   239

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  42
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  35
/* YYNRULES -- Number of rules.  */
#define YYNRULES  98
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  178

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   296


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39,    40,    41
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   148,   148,   156,   162,   167,   174,   192,   203,   206,
     212,   224,   247,   250,   256,   259,   267,   273,   284,   289,
     298,   302,   313,   319,   342,   365,   384,   404,   435,   443,
     448,   453,   461,   464,   470,   473,   482,   488,   492,   498,
     504,   510,   516,   520,   524,   528,   534,   538,   545,   551,
     554,   560,   563,   569,   572,   575,   581,   584,   587,   590,
     593,   599,   603,   612,   615,   621,   625,   632,   635,   638,
     647,   653,   659,   663,   666,   669,   672,   675,   691,   709,
     712,   717,   720,   723,   729,   732,   738,   741,   744,   749,
     756,   760,   766,   778,   782,   789,   798,   806,   809
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_INT", "T_VOID", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_FOR",
  "T_BREAK", "T_CONTINUE", "T_CONST", "T_STATIC", "T_SEMICOLON",
  "T_L_PAREN", "T_R_PAREN", "T_L_BRACE", "T_R_BRACE", "T_L_BRACKET",
  "T_R_BRACKET", "T_COMMA", "T_ASSIGN", "T_SUB", "T_ADD", "T_MUL", "T_DIV",
  "T_MOD", "T_EQ", "T_NE", "T_LT", "T_LE", "T_GT", "T_GE", "T_AND", "T_OR",
  "T_NOT", "T_INC", "T_DEC", "LOWER_THAN_ELSE", "$accept", "CompileUnit",
  "FuncDef", "FuncFParams", "FuncFParam", "FuncArrayDimsOpt",
  "FuncArrayDims", "Block", "BlockItemList", "BlockItem", "VarDecl",
  "VarDeclExpr", "VarDef", "VarArrayDims", "BasicType", "Statement",
  "Expr", "LOrExp", "LAndExp", "EqExp", "RelExp", "AddExp", "AddOp",
  "MulExp", "MulOp", "UnaryExp", "ForInitOpt", "ForInit", "ForCondOpt",
  "ForStepOpt", "ForExpr", "PrimaryExp", "RealParamList", "LVal",
  "ArraySubscripts", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-145)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     110,  -145,  -145,    91,    49,    80,  -145,  -145,     5,    -3,
      18,    91,    18,  -145,  -145,  -145,  -145,    18,    -1,  -145,
     152,  -145,    18,  -145,  -145,    13,    21,   168,   153,  -145,
      37,    99,  -145,    54,    51,  -145,   117,   168,   168,   168,
      71,    71,  -145,    46,    84,    78,   130,   111,   172,  -145,
    -145,   102,   120,   168,    32,  -145,    37,    91,   129,  -145,
      64,   168,   138,   157,  -145,  -145,   163,  -145,  -145,   168,
     168,   168,   168,   168,   168,   168,   168,  -145,  -145,   168,
    -145,  -145,  -145,   168,  -145,  -145,   156,  -145,    89,   171,
     177,   180,   189,   193,  -145,  -145,  -145,   141,  -145,  -145,
      18,  -145,   194,   -10,  -145,  -145,   190,  -145,  -145,   103,
     191,   168,  -145,    84,    78,   130,   130,   111,   111,   111,
     111,   172,  -145,  -145,  -145,   195,   168,   168,    73,  -145,
    -145,  -145,  -145,  -145,   168,   199,  -145,   168,  -145,   192,
    -145,   197,   198,   200,  -145,   205,  -145,  -145,    26,   206,
     221,  -145,   204,  -145,  -145,   179,   179,   168,   168,  -145,
     207,   223,   218,  -145,  -145,   212,  -145,  -145,   208,   179,
     168,  -145,  -145,  -145,   213,  -145,   179,  -145
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    34,    35,     0,     0,     0,     2,     3,     0,     0,
       0,     0,     0,     1,     4,     5,    22,     0,    28,    23,
      28,    24,     0,    25,    27,     0,     0,     0,    30,    26,
       0,     0,     8,     0,     0,    91,    95,     0,     0,     0,
       0,     0,    29,    48,    49,    51,    53,    56,    61,    65,
      70,    92,     0,     0,     0,     6,     0,     0,    10,    32,
       0,     0,    96,     0,    71,    72,    95,    73,    74,     0,
       0,     0,     0,     0,     0,     0,     0,    64,    63,     0,
      67,    68,    69,     0,    75,    76,     0,    31,     0,     0,
       0,     0,     0,     0,    41,    16,    39,     0,    18,    21,
       0,    20,     0,    92,     7,     9,     0,    77,    93,     0,
       0,     0,    90,    50,    52,    54,    55,    57,    58,    59,
      60,    62,    66,    33,    37,     0,     0,     0,    79,    46,
      47,    17,    19,    40,     0,    12,    78,     0,    97,     0,
      36,     0,     0,    83,    81,     0,    80,    82,    92,     0,
       0,    11,    13,    94,    98,     0,     0,    84,     0,    38,
       0,     0,    42,    44,    85,     0,    89,    14,     0,     0,
      86,    15,    43,    87,     0,    88,     0,    45
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -145,  -145,   227,  -145,   176,  -145,  -145,   -15,  -145,   137,
     135,   107,    52,  -145,     2,  -144,   -27,  -145,   167,   169,
     131,    94,  -145,   158,  -145,   -30,  -145,  -145,  -145,  -145,
      68,  -145,  -145,   -37,  -145
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,     5,     6,    31,    32,   151,   152,    96,    97,    98,
      99,     8,    19,    28,   100,   101,   102,    43,    44,    45,
      46,    47,    79,    48,    83,    49,   145,   146,   165,   174,
     147,    50,   109,    51,    62
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      42,    18,     9,    67,    68,    10,    12,     9,    64,    65,
      63,   162,   163,    22,   134,    55,    25,   103,     1,     2,
      26,    16,    20,    27,    34,   172,    87,    33,    17,    84,
      85,    30,   177,   108,   110,    35,    36,     1,     2,    88,
      89,   104,    90,    91,    92,    93,     3,     4,    94,    37,
     158,    54,    95,   122,     1,     2,    54,    38,    58,    33,
     103,   125,    21,    11,    23,    84,    85,    35,    36,    24,
      39,    40,    41,    59,    29,    66,    35,    36,     1,     2,
      13,    37,   107,    69,   139,     1,     2,     3,     4,    38,
      37,   148,    35,    36,     3,     4,     1,     2,    38,   141,
     142,   144,    39,    40,    41,   124,    37,   149,    71,    72,
     153,    39,    40,    41,    38,     1,     2,    56,   103,   103,
      70,   136,    57,    86,     3,     4,   137,    39,    40,    41,
     164,   166,   103,   148,    60,     7,    77,    78,    61,   103,
      15,    84,    85,   173,    35,    36,     1,     2,    88,    89,
     106,    90,    91,    92,    93,     3,     4,    94,    37,   111,
      54,   131,    73,    74,    75,    76,    38,   117,   118,   119,
     120,    35,    36,    26,    52,   112,    27,    53,   123,    39,
      40,    41,    35,    36,    61,    37,    88,    89,   126,    90,
      91,    92,    93,    38,   127,    94,    37,   128,    54,    80,
      81,    82,   115,   116,    38,   129,    39,    40,    41,   130,
     133,   140,   135,   138,   154,   155,   156,    39,    40,    41,
     150,   157,   159,    17,   160,   161,   168,   169,   170,   167,
     171,   176,    14,   105,   132,   143,   113,   121,   175,   114
};

static const yytype_uint8 yycheck[] =
{
      27,     4,     0,    40,    41,     3,     4,     5,    38,    39,
      37,   155,   156,    11,    24,    30,    17,    54,     5,     6,
      21,    16,     4,    24,     3,   169,    53,    25,    23,    39,
      40,    18,   176,    60,    61,     3,     4,     5,     6,     7,
       8,    56,    10,    11,    12,    13,    14,    15,    16,    17,
      24,    19,    20,    83,     5,     6,    19,    25,     4,    57,
      97,    88,    10,    14,    12,    39,    40,     3,     4,    17,
      38,    39,    40,    22,    22,     4,     3,     4,     5,     6,
       0,    17,    18,    37,   111,     5,     6,    14,    15,    25,
      17,   128,     3,     4,    14,    15,     5,     6,    25,   126,
     127,   128,    38,    39,    40,    16,    17,   134,    30,    31,
     137,    38,    39,    40,    25,     5,     6,    18,   155,   156,
      36,    18,    23,     3,    14,    15,    23,    38,    39,    40,
     157,   158,   169,   170,    17,     0,    25,    26,    21,   176,
       5,    39,    40,   170,     3,     4,     5,     6,     7,     8,
      21,    10,    11,    12,    13,    14,    15,    16,    17,    21,
      19,    20,    32,    33,    34,    35,    25,    73,    74,    75,
      76,     3,     4,    21,    21,    18,    24,    24,    22,    38,
      39,    40,     3,     4,    21,    17,     7,     8,    17,    10,
      11,    12,    13,    25,    17,    16,    17,    17,    19,    27,
      28,    29,    71,    72,    25,    16,    38,    39,    40,    16,
      16,    16,    22,    22,    22,    18,    18,    38,    39,    40,
      21,    16,    16,    23,     3,    21,     3,     9,    16,    22,
      22,    18,     5,    57,    97,   128,    69,    79,   170,    70
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     5,     6,    14,    15,    43,    44,    52,    53,    56,
      56,    14,    56,     0,    44,    52,    16,    23,     4,    54,
       4,    54,    56,    54,    54,    17,    21,    24,    55,    54,
      18,    45,    46,    56,     3,     3,     4,    17,    25,    38,
      39,    40,    58,    59,    60,    61,    62,    63,    65,    67,
      73,    75,    21,    24,    19,    49,    18,    23,     4,    22,
      17,    21,    76,    58,    67,    67,     4,    75,    75,    37,
      36,    30,    31,    32,    33,    34,    35,    25,    26,    64,
      27,    28,    29,    66,    39,    40,     3,    58,     7,     8,
      10,    11,    12,    13,    16,    20,    49,    50,    51,    52,
      56,    57,    58,    75,    49,    46,    21,    18,    58,    74,
      58,    21,    18,    60,    61,    62,    62,    63,    63,    63,
      63,    65,    67,    22,    16,    58,    17,    17,    17,    16,
      16,    20,    51,    16,    24,    22,    18,    23,    22,    58,
      16,    58,    58,    53,    58,    68,    69,    72,    75,    58,
      21,    47,    48,    58,    22,    18,    18,    16,    24,    16,
       3,    21,    57,    57,    58,    70,    58,    22,     3,     9,
      16,    22,    57,    58,    71,    72,    18,    57
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    42,    43,    43,    43,    43,    44,    44,    45,    45,
      46,    46,    47,    47,    48,    48,    49,    49,    50,    50,
      51,    51,    52,    53,    53,    53,    53,    53,    54,    54,
      54,    54,    55,    55,    56,    56,    57,    57,    57,    57,
      57,    57,    57,    57,    57,    57,    57,    57,    58,    59,
      59,    60,    60,    61,    61,    61,    62,    62,    62,    62,
      62,    63,    63,    64,    64,    65,    65,    66,    66,    66,
      67,    67,    67,    67,    67,    67,    67,    67,    67,    68,
      68,    69,    69,    69,    70,    70,    71,    71,    71,    72,
      73,    73,    73,    74,    74,    75,    75,    76,    76
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     1,     3,
       2,     5,     0,     1,     3,     4,     2,     3,     1,     2,
       1,     1,     2,     2,     3,     3,     4,     3,     1,     3,
       2,     4,     3,     4,     1,     1,     3,     2,     4,     1,
       2,     1,     5,     7,     5,     9,     2,     2,     1,     1,
       3,     1,     3,     1,     3,     3,     1,     3,     3,     3,
       3,     1,     3,     1,     1,     1,     3,     1,     1,     1,
       1,     2,     2,     2,     2,     2,     2,     3,     4,     0,
       1,     1,     1,     1,     0,     1,     0,     1,     1,     3,
       3,     1,     1,     1,     3,     1,     2,     3,     4
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 148 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1350 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 156 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1361 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 162 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1371 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 167 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1380 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID T_L_PAREN T_R_PAREN Block  */
#line 174 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                    {

		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = ast_node::create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1403 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID T_L_PAREN FuncFParams T_R_PAREN Block  */
#line 192 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                               {
		// 函数定义带形参
		type_attr funcReturnType = (yyvsp[-5].type);
		var_id_attr funcId = (yyvsp[-4].var_id);
		ast_node * formalParamsNode = (yyvsp[-2].node);
		ast_node * blockNode = (yyvsp[0].node);
		(yyval.node) = ast_node::create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1416 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FuncFParams: FuncFParam  */
#line 203 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
	}
#line 1424 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FuncFParams: FuncFParams T_COMMA FuncFParam  */
#line 206 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                         {
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1432 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FuncFParam: BasicType T_ID  */
#line 212 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		if ((yyvsp[-1].type).type == BasicType::TYPE_VOID) {
			yyerror("function parameter type cannot be void");
			YYERROR;
		}
		ast_node * type_node = ast_node::create_type_node((yyvsp[-1].type));
		ast_node * name_node = ast_node::New(std::string((yyvsp[0].var_id).id), (yyvsp[0].var_id).lineno);
		free((yyvsp[0].var_id).id);
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM, type_node, name_node);
		(yyval.node)->type = type_node->type;
		(yyval.node)->name = name_node->name;
	}
#line 1449 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FuncFParam: BasicType T_ID T_L_BRACKET T_R_BRACKET FuncArrayDimsOpt  */
#line 224 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                  {
		if ((yyvsp[-4].type).type == BasicType::TYPE_VOID) {
			yyerror("function parameter type cannot be void");
			YYERROR;
		}
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);
		free((yyvsp[-3].var_id).id);

		ast_node * dims_node = ast_node::createArrayDimsNode(ast_node::New(digit_int_attr{0, (yyvsp[-3].var_id).lineno}));
		if ((yyvsp[0].node)) {
			for (auto child: (yyvsp[0].node)->sons) {
				dims_node->insert_son_node(child);
			}
		}

		ast_node * type_node = ast_node::create_type_node((yyvsp[-4].type), dims_node, true);
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM, type_node, name_node);
		(yyval.node)->type = type_node->type;
		(yyval.node)->name = name_node->name;
	}
#line 1474 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* FuncArrayDimsOpt: %empty  */
#line 247 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
			(yyval.node) = nullptr;
		}
#line 1482 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* FuncArrayDimsOpt: FuncArrayDims  */
#line 251 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
			(yyval.node) = (yyvsp[0].node);
		}
#line 1490 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* FuncArrayDims: T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 256 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_ARRAY_DIMS, ast_node::New((yyvsp[-1].integer_num)));
	}
#line 1498 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* FuncArrayDims: FuncArrayDims T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 259 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                        {
		(yyval.node) = (yyvsp[-3].node)->insert_son_node(ast_node::New((yyvsp[-1].integer_num)));
	}
#line 1506 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* Block: T_L_BRACE T_R_BRACE  */
#line 267 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_BLOCK);
	}
#line 1517 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* Block: T_L_BRACE BlockItemList T_R_BRACE  */
#line 273 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                            {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1528 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* BlockItemList: BlockItem  */
#line 284 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node));
	}
#line 1538 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* BlockItemList: BlockItemList BlockItem  */
#line 289 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1547 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* BlockItem: Statement  */
#line 298 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1556 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* BlockItem: VarDecl  */
#line 302 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1565 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* VarDecl: VarDeclExpr T_SEMICOLON  */
#line 313 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1573 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* VarDeclExpr: BasicType VarDef  */
#line 319 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		if ((yyvsp[-1].type).type == BasicType::TYPE_VOID) {
			yyerror("variable type cannot be void");
			YYERROR;
		}

		ast_node * dims_node = nullptr;
		if (!(yyvsp[0].node)->sons.empty() && (yyvsp[0].node)->sons[0] && (yyvsp[0].node)->sons[0]->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			dims_node = (yyvsp[0].node)->sons[0];
		}

		// 创建类型节点
		ast_node * type_node = ast_node::create_type_node((yyvsp[-1].type), dims_node);

		// 创建变量定义节点
		ast_node * decl_node = ast_node::New(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;
		decl_node->isConstDecl = false;
		decl_node->isStaticDecl = false;

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = ast_node::create_var_decl_stmt_node(decl_node);
	}
#line 1601 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* VarDeclExpr: T_CONST BasicType VarDef  */
#line 342 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                   {
		if ((yyvsp[-1].type).type == BasicType::TYPE_VOID) {
			yyerror("variable type cannot be void");
			YYERROR;
		}

		ast_node * dims_node = nullptr;
		if (!(yyvsp[0].node)->sons.empty() && (yyvsp[0].node)->sons[0] && (yyvsp[0].node)->sons[0]->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			dims_node = (yyvsp[0].node)->sons[0];
		}

		// 创建类型节点
		ast_node * type_node = ast_node::create_type_node((yyvsp[-1].type), dims_node);

		// 创建变量定义节点
		ast_node * decl_node = ast_node::New(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;
		decl_node->isConstDecl = true;
		decl_node->isStaticDecl = false;

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = ast_node::create_var_decl_stmt_node(decl_node);
	}
#line 1629 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* VarDeclExpr: T_STATIC BasicType VarDef  */
#line 365 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                    {
		if ((yyvsp[-1].type).type == BasicType::TYPE_VOID) {
			yyerror("variable type cannot be void");
			YYERROR;
		}

		ast_node * dims_node = nullptr;
		if (!(yyvsp[0].node)->sons.empty() && (yyvsp[0].node)->sons[0] && (yyvsp[0].node)->sons[0]->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			dims_node = (yyvsp[0].node)->sons[0];
		}

		ast_node * type_node = ast_node::create_type_node((yyvsp[-1].type), dims_node);
		ast_node * decl_node = ast_node::New(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;
		decl_node->isConstDecl = false;
		decl_node->isStaticDecl = true;

		(yyval.node) = ast_node::create_var_decl_stmt_node(decl_node);
	}
#line 1653 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* VarDeclExpr: T_STATIC T_CONST BasicType VarDef  */
#line 384 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                            {
		if ((yyvsp[-1].type).type == BasicType::TYPE_VOID) {
			yyerror("variable type cannot be void");
			YYERROR;
		}

		ast_node * dims_node = nullptr;
		if (!(yyvsp[0].node)->sons.empty() && (yyvsp[0].node)->sons[0] && (yyvsp[0].node)->sons[0]->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			dims_node = (yyvsp[0].node)->sons[0];
		}

		ast_node * type_node = ast_node::create_type_node((yyvsp[-1].type), dims_node);
		ast_node * decl_node = ast_node::New(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;
		decl_node->isConstDecl = true;
		decl_node->isStaticDecl = true;

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = ast_node::create_var_decl_stmt_node(decl_node);
	}
#line 1678 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* VarDeclExpr: VarDeclExpr T_COMMA VarDef  */
#line 404 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                     {
		// 创建类型节点：每个VarDef独立按是否带数组维度确定类型
		type_attr baseTypeAttr;
		baseTypeAttr.lineno = (yyvsp[0].node)->line_no;
		if ((yyvsp[-2].node)->type && (yyvsp[-2].node)->type->isVoidType()) {
			baseTypeAttr.type = BasicType::TYPE_VOID;
		} else {
			baseTypeAttr.type = BasicType::TYPE_INT;
		}

		ast_node * dims_node = nullptr;
		if (!(yyvsp[0].node)->sons.empty() && (yyvsp[0].node)->sons[0] && (yyvsp[0].node)->sons[0]->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			dims_node = (yyvsp[0].node)->sons[0];
		}

		ast_node * type_node = ast_node::create_type_node(baseTypeAttr, dims_node);

		// 创建变量定义节点
		ast_node * decl_node = ast_node::New(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;
		if (!(yyvsp[-2].node)->sons.empty()) {
			decl_node->isConstDecl = (yyvsp[-2].node)->sons[0]->isConstDecl;
			decl_node->isStaticDecl = (yyvsp[-2].node)->sons[0]->isStaticDecl;
		}

		// 插入到变量声明语句
		(yyval.node) = (yyvsp[-2].node)->insert_son_node(decl_node);
	}
#line 1711 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* VarDef: T_ID  */
#line 435 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
              {
		// 变量ID

		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 1724 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* VarDef: T_ID T_ASSIGN Expr  */
#line 443 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
		(yyval.node)->insert_son_node((yyvsp[0].node));
		free((yyvsp[-2].var_id).id);
	}
#line 1734 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* VarDef: T_ID VarArrayDims  */
#line 448 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		(yyval.node)->insert_son_node((yyvsp[0].node));
		free((yyvsp[-1].var_id).id);
	}
#line 1744 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* VarDef: T_ID VarArrayDims T_ASSIGN Expr  */
#line 453 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                          {
		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		(yyval.node)->insert_son_node((yyvsp[-2].node));
		(yyval.node)->insert_son_node((yyvsp[0].node));
		free((yyvsp[-3].var_id).id);
	}
#line 1755 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* VarArrayDims: T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 461 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                               {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_ARRAY_DIMS, ast_node::New((yyvsp[-1].integer_num)));
	}
#line 1763 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* VarArrayDims: VarArrayDims T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 464 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                       {
		(yyval.node) = (yyvsp[-3].node)->insert_son_node(ast_node::New((yyvsp[-1].integer_num)));
	}
#line 1771 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* BasicType: T_INT  */
#line 470 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1779 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* BasicType: T_VOID  */
#line 473 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1787 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* Statement: T_RETURN Expr T_SEMICOLON  */
#line 482 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                      {
		// 返回语句

		// 创建返回节点AST_OP_RETURN，其孩子为Expr，即$2
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_RETURN, (yyvsp[-1].node));
	}
#line 1798 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* Statement: T_RETURN T_SEMICOLON  */
#line 488 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		// 无返回值的return语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_RETURN);
	}
#line 1807 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* Statement: LVal T_ASSIGN Expr T_SEMICOLON  */
#line 492 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                         {
		// 赋值语句

		// 创建一个AST_OP_ASSIGN类型的中间节点，孩子为LVal($1)和Expr($3)
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1818 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* Statement: Block  */
#line 498 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 语句块

		// 内部已创建block节点，直接传递给Statement
		(yyval.node) = (yyvsp[0].node);
	}
#line 1829 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* Statement: Expr T_SEMICOLON  */
#line 504 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                           {
		// 表达式语句

		// 内部已创建表达式，直接传递给Statement
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1840 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* Statement: T_SEMICOLON  */
#line 510 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		// 空语句

		// 直接返回空指针，需要再把语句加入到语句块时要注意判断，空语句不要加入
		(yyval.node) = nullptr;
	}
#line 1851 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement  */
#line 516 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                        {
		// if语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1860 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement T_ELSE Statement  */
#line 520 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                   {
		// if-else语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1869 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* Statement: T_WHILE T_L_PAREN Expr T_R_PAREN Statement  */
#line 524 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                     {
		// while语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1878 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* Statement: T_FOR T_L_PAREN ForInitOpt T_SEMICOLON ForCondOpt T_SEMICOLON ForStepOpt T_R_PAREN Statement  */
#line 528 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                                                       {
		ast_node * initNode = (yyvsp[-6].node) ? (yyvsp[-6].node) : make_for_missing_marker();
		ast_node * condNode = (yyvsp[-4].node) ? (yyvsp[-4].node) : make_for_missing_marker();
		ast_node * stepNode = (yyvsp[-2].node) ? (yyvsp[-2].node) : make_for_missing_marker();
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_FOR, initNode, condNode, stepNode, (yyvsp[0].node));
	}
#line 1889 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* Statement: T_BREAK T_SEMICOLON  */
#line 534 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// break语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_BREAK);
	}
#line 1898 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* Statement: T_CONTINUE T_SEMICOLON  */
#line 538 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                 {
		// continue语句
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_CONTINUE);
	}
#line 1907 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* Expr: LOrExp  */
#line 545 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1915 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* LOrExp: LAndExp  */
#line 551 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1923 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* LOrExp: LOrExp T_OR LAndExp  */
#line 554 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_LOR, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1931 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* LAndExp: EqExp  */
#line 560 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1939 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* LAndExp: LAndExp T_AND EqExp  */
#line 563 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_LAND, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1947 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* EqExp: RelExp  */
#line 569 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1955 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* EqExp: EqExp T_EQ RelExp  */
#line 572 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_EQ, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1963 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* EqExp: EqExp T_NE RelExp  */
#line 575 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_NE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1971 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* RelExp: AddExp  */
#line 581 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1979 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* RelExp: RelExp T_LT AddExp  */
#line 584 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_LT, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1987 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* RelExp: RelExp T_LE AddExp  */
#line 587 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_LE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1995 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* RelExp: RelExp T_GT AddExp  */
#line 590 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_GT, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2003 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* RelExp: RelExp T_GE AddExp  */
#line 593 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_GE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2011 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* AddExp: MulExp  */
#line 599 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 直接传递给归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 2020 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* AddExp: AddExp AddOp MulExp  */
#line 603 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 左递归形式可通过加减连接多个乘法表达式

		// 创建加减运算节点，孩子为AddExp($1)和MulExp($3)
		(yyval.node) = ast_node::New(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2031 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* AddOp: T_ADD  */
#line 612 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_ADD;
	}
#line 2039 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* AddOp: T_SUB  */
#line 615 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_SUB;
	}
#line 2047 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* MulExp: UnaryExp  */
#line 621 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
		// 一元表达式
		(yyval.node) = (yyvsp[0].node);
	}
#line 2056 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* MulExp: MulExp MulOp UnaryExp  */
#line 625 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                {
		// 左递归形式可通过乘除模连接多个一元表达式
		(yyval.node) = ast_node::New(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2065 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* MulOp: T_MUL  */
#line 632 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_MUL;
	}
#line 2073 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* MulOp: T_DIV  */
#line 635 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_DIV;
	}
#line 2081 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* MulOp: T_MOD  */
#line 638 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_MOD;
	}
#line 2089 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* UnaryExp: PrimaryExp  */
#line 647 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 2100 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* UnaryExp: T_SUB UnaryExp  */
#line 653 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         {
		// 单目求负，负数字面量按“无符号数 + 求负符号”处理
		digit_int_attr zeroAttr{0, (yyvsp[0].node) ? (yyvsp[0].node)->line_no : -1};
		ast_node * zeroNode = ast_node::New(zeroAttr);
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_SUB, zeroNode, (yyvsp[0].node));
	}
#line 2111 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* UnaryExp: T_NOT UnaryExp  */
#line 659 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         {
		// 逻辑非
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_LNOT, (yyvsp[0].node));
	}
#line 2120 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* UnaryExp: T_INC LVal  */
#line 663 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		(yyval.node) = make_inc_dec_expr((yyvsp[0].node), true, false);
	}
#line 2128 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* UnaryExp: T_DEC LVal  */
#line 666 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		(yyval.node) = make_inc_dec_expr((yyvsp[0].node), false, false);
	}
#line 2136 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* UnaryExp: LVal T_INC  */
#line 669 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		(yyval.node) = make_inc_dec_expr((yyvsp[-1].node), true, true);
	}
#line 2144 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* UnaryExp: LVal T_DEC  */
#line 672 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		(yyval.node) = make_inc_dec_expr((yyvsp[-1].node), false, true);
	}
#line 2152 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* UnaryExp: T_ID T_L_PAREN T_R_PAREN  */
#line 675 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                   {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = ast_node::create_func_call(name_node, paramListNode);

	}
#line 2173 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* UnaryExp: T_ID T_L_PAREN RealParamList T_R_PAREN  */
#line 691 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                 {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = ast_node::create_func_call(name_node, paramListNode);
	}
#line 2193 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 79: /* ForInitOpt: %empty  */
#line 709 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
			(yyval.node) = nullptr;
		}
#line 2201 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 80: /* ForInitOpt: ForInit  */
#line 712 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
			(yyval.node) = (yyvsp[0].node);
		}
#line 2209 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 81: /* ForInit: Expr  */
#line 717 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 2217 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 82: /* ForInit: ForExpr  */
#line 720 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
		(yyval.node) = (yyvsp[0].node);
	}
#line 2225 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 83: /* ForInit: VarDeclExpr  */
#line 723 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		(yyval.node) = (yyvsp[0].node);
	}
#line 2233 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 84: /* ForCondOpt: %empty  */
#line 729 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
			(yyval.node) = nullptr;
		}
#line 2241 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 85: /* ForCondOpt: Expr  */
#line 732 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
			(yyval.node) = (yyvsp[0].node);
		}
#line 2249 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 86: /* ForStepOpt: %empty  */
#line 738 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
			(yyval.node) = nullptr;
		}
#line 2257 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 87: /* ForStepOpt: Expr  */
#line 741 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
			(yyval.node) = (yyvsp[0].node);
		}
#line 2265 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 88: /* ForStepOpt: ForExpr  */
#line 744 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
			(yyval.node) = (yyvsp[0].node);
		}
#line 2273 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 89: /* ForExpr: LVal T_ASSIGN Expr  */
#line 749 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2281 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 90: /* PrimaryExp: T_L_PAREN Expr T_R_PAREN  */
#line 756 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                       {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 2290 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 91: /* PrimaryExp: T_DIGIT  */
#line 760 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量

		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 2301 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 92: /* PrimaryExp: LVal  */
#line 766 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 2312 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 93: /* RealParamList: Expr  */
#line 778 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 2321 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 94: /* RealParamList: RealParamList T_COMMA Expr  */
#line 782 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                     {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2330 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 95: /* LVal: T_ID  */
#line 789 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 2344 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 96: /* LVal: T_ID ArraySubscripts  */
#line 798 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		(yyval.node) = ast_node::createArrayAccessNode(id_node, (yyvsp[0].node));
		free((yyvsp[-1].var_id).id);
	}
#line 2354 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 97: /* ArraySubscripts: T_L_BRACKET Expr T_R_BRACKET  */
#line 806 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                               {
		(yyval.node) = ast_node::New(ast_operator_type::AST_OP_ARRAY_DIMS, (yyvsp[-1].node));
	}
#line 2362 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 98: /* ArraySubscripts: ArraySubscripts T_L_BRACKET Expr T_R_BRACKET  */
#line 809 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                       {
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 2370 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2374 "/home/faith/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 814 "/home/faith/exp04-minic-expr/frontend/flexbison/MiniC.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
